name: ASWF Logos + Artwork
title: Academy Software Foundation (ASWF) Logos
description: >-
  Logos and artwork for Academy Software Foundation (ASWF) and it's hosted projects

# Settings
github_repo: https://github.com/AcademySoftwareFoundation/artwork

