title: Academy Software Foundation (ASWF) Logos
description: >-
  Logos and artwork for Academy Software Foundation (ASWF) and it's hosted projects

# Settings
primary_logo: other/aswf/logo/aqua/aswf-logo-aqua.svg
header_logo: other/aswf/logo/white/aswf-logo-white.svg
github_repo: https://github.com/AcademySoftwareFoundation/artwork
section_image: assets/img/section-background.jpg
theme_color_1: 36b0c9
theme_color_2: 159957
favicon: assets/img/favicon.png
# categories of logos, for grouping on main logo page. Must match level: in front matter of each logoset README.md file
logo_categories:
  - Projects
  - Working Groups
  - Other Logos
ga_tracking_id: 360578303
clotributor_category_default: Visual Effects and Computer Graphics

defaults:
  - scope:
      path: "other"     # directory (relative to site root)
      type: "pages"    # usually "pages"
    values:
      layout: "logos"
      level: "Other Logos"
  - scope:
      path: "projects"     # directory (relative to site root)
      type: "pages"    # usually "pages"
    values:
      layout: "logos"
      level: "Projects"
  - scope:
      path: "working-groups"     # directory (relative to site root)
      type: "pages"    # usually "pages"
    values:
      layout: "logos"
      level: "Working Groups"

# don't touch ;-)
readme_index:
  with_frontmatter: true
plugins:
  - jekyll-remote-theme
remote_theme: jmertic/artwork-template
